name: Update rb-ubuntu base image

on:
  schedule:
    - cron: "50 10 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    if: github.repository == 'jvm-repo-rebuild/reproducible-central'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Log into ghcr.io registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: bin/docker
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/jvm-repo-rebuild/rb-ubuntu:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Status Diffoscope Before
        run: |
          docker image ls registry.salsa.debian.org/reproducible-builds/diffoscope:latest
          docker run --rm registry.salsa.debian.org/reproducible-builds/diffoscope:latest --version
          docker image ls ghcr.io/jvm-repo-rebuild/diffoscope:latest
          docker run --rm ghcr.io/jvm-repo-rebuild/diffoscope:latest --version

      - name: Copy Diffoscope to ghcr.io
        uses: truemark/skopeo-copy-action@v1
        with:
          src-image: "docker://registry.salsa.debian.org/reproducible-builds/diffoscope:latest"
          dest-image: "docker://ghcr.io/jvm-repo-rebuild/diffoscope:latest"
          dest-username: ${{ github.actor }}
          dest-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Status Diffoscope After
        run: |
          docker image ls registry.salsa.debian.org/reproducible-builds/diffoscope:latest
          docker run --rm registry.salsa.debian.org/reproducible-builds/diffoscope:latest --version
          docker image ls ghcr.io/jvm-repo-rebuild/diffoscope:latest
          docker run --rm ghcr.io/jvm-repo-rebuild/diffoscope:latest --version
